// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3KGnRFUQrP4IcvBqUi5UC8zuvs3GapRs',
    appId: '1:615802873958:web:bcdd729084de7f2a5c25a7',
    messagingSenderId: '615802873958',
    projectId: 'my-flutter-project-99b4b',
    authDomain: 'my-flutter-project-99b4b.firebaseapp.com',
    storageBucket: 'my-flutter-project-99b4b.appspot.com',
    measurementId: 'G-V2WK3R9P1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNR5nL_4GIsch21X5CEAa3xuRiWYx4nw8',
    appId: '1:615802873958:android:febc079ff6c79e4a5c25a7',
    messagingSenderId: '615802873958',
    projectId: 'my-flutter-project-99b4b',
    storageBucket: 'my-flutter-project-99b4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQGpXKZJg-IBuhg9p8I_stUPECvuLRORM',
    appId: '1:615802873958:ios:19b442bb79c75b405c25a7',
    messagingSenderId: '615802873958',
    projectId: 'my-flutter-project-99b4b',
    storageBucket: 'my-flutter-project-99b4b.appspot.com',
    iosClientId: '615802873958-i4g771htiqnu1sm2iep4tjtt3mub0mdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQGpXKZJg-IBuhg9p8I_stUPECvuLRORM',
    appId: '1:615802873958:ios:19b442bb79c75b405c25a7',
    messagingSenderId: '615802873958',
    projectId: 'my-flutter-project-99b4b',
    storageBucket: 'my-flutter-project-99b4b.appspot.com',
    iosClientId: '615802873958-i4g771htiqnu1sm2iep4tjtt3mub0mdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
